cache:
  bundler: true
  directories:
  - tmp/cache/assets/test
group: edge
language: ruby
services:
  - redis-server
sudo: false
before_script: "./bin/rake db:setup RAILS_ENV=test"
script: "./bin/rake RAILS_ENV=test"
before_install:
- gem update --system
- gem install bundler
