default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>

development:
  <<: *default
  database: signonotron2_development

test: &test
  <<: *default
  database: signonotron2_test
