development:
  secret_key: 'fake-secret-key'

test:
  secret_key: 'fake-secret-key'
  stretches: 1

staging:
  secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>

production:
  secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
